add readinessprobe

diff --git a/kibana/kibana-deploy.yaml b/kibana/kibana-deploy.yaml
--- a/kibana/kibana-deploy.yaml
+++ b/kibana/kibana-deploy.yaml
@@ -24,7 +24,7 @@ spec:
     spec:
       containers:
         - name: wazuh-kibana
-          image: 'wazuh/wazuh-kibana:3.13.0_7.7.1'
+          image: "wazuh/wazuh-kibana:3.13.0_7.7.1"
           resources:
             requests:
               cpu: 200m
@@ -37,6 +37,38 @@ spec:
               name: kibana
           env:
             - name: ELASTICSEARCH_URL
-              value: 'http://elasticsearch:9200'
+              value: "http://elasticsearch:9200"
             - name: NODE_OPTIONS
-              value: '--max-old-space-size=512'
+              value: "--max-old-space-size=512"
+
+          # Add readinessProbe
+          readinessProbe:
+            failureThreshold: 3
+            initialDelaySeconds: 10
+            periodSeconds: 10
+            successThreshold: 3
+            timeoutSeconds: 5
+            exec:
+              command:
+                - sh
+                - -c
+                - |
+                  #!/usr/bin/env bash -e
+                  http () {
+                      local path="${1}"
+                      set -- -XGET -s --fail -L
+
+                      if [ -n "${ELASTICSEARCH_USERNAME}" ] && [ -n "${ELASTICSEARCH_PASSWORD}" ]; then
+                        set -- "$@" -u "${ELASTICSEARCH_USERNAME}:${ELASTICSEARCH_PASSWORD}"
+                      fi
+
+                      STATUS=$(curl --output /dev/null --write-out "%{http_code}" -k "$@" "http://localhost:5601${path}")
+                      if [[ "${STATUS}" -eq 200 ]]; then
+                        exit 0
+                      fi
+
+                      echo "Error: Got HTTP code ${STATUS} but expected a 200"
+                      exit 1
+                  }
+
+                  http "/app/kibana"
